import { google } from 'googleapis'
import { format } from 'date-fns'

const CALENDAR_ID = process.env.GOOGLE_CALENDAR_ID ||
  '72bf6ae390fb09d1e0a117dbaf421799be6bcc3b21ec2b7c3e2d7a65e65f9dc5@group.calendar.google.com'

function getAuth() {
  const credentials = process.env.GOOGLE_SERVICE_ACCOUNT_JSON
    ? JSON.parse(process.env.GOOGLE_SERVICE_ACCOUNT_JSON)
    : {
        client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
        private_key: process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, '\n'),
      }

  return new google.auth.JWT({
    email: credentials.client_email,
    key: credentials.private_key,
    scopes: ['https://www.googleapis.com/auth/calendar'],
  })
}

function parseTime(date: Date, timeStr: string): Date {
  const [h, m] = timeStr.split(':').map(Number)
  const d = new Date(date)
  d.setHours(h, m, 0, 0)
  return d
}

export async function createCalendarEvent(booking: {
  id: string
  shootDate: Date | string
  callTime: string
  estimatedWrap?: string | null
  shootType: string
  locationName?: string | null
  producer: string
  assignedEmails?: string[]
  outlet: { code: string; name: string }
  program: { code: string; name: string }
  episodes: Array<{ episodeId: string; title: string }>
  crewRequired: string[]
  agencyRef?: string | null
  notes?: string | null
}): Promise<string | null> {
  if (!process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL && !process.env.GOOGLE_SERVICE_ACCOUNT_JSON) {
    console.warn('Google Calendar: no credentials configured')
    return null
  }

  try {
    const auth = getAuth()
    const calendar = google.calendar({ version: 'v3', auth })

    const shootDate = new Date(booking.shootDate)
    const startTime = parseTime(shootDate, booking.callTime)
    const endTime = booking.estimatedWrap
      ? parseTime(shootDate, booking.estimatedWrap)
      : new Date(startTime.getTime() + 4 * 60 * 60 * 1000)

    const epCount = booking.episodes.length
    // Location = the actual room/venue (independent of Shoot Type)
    const location = booking.locationName || '—'
    const shootTypeLabel = booking.shootType.replace('_', ' ')

    const title = epCount === 1
      ? `[${booking.outlet.code}] ${booking.program.name} — ${booking.episodes[0].title}`
      : `[${booking.outlet.code}] ${booking.program.name} — ${epCount} EPs`

    const epList = booking.episodes.map(e => `• ${e.episodeId} — ${e.title}`).join('\n')
    const description = `Production Booking
Episode IDs:
${epList}

Outlet: ${booking.outlet.name} (${booking.outlet.code})
Program: ${booking.program.name} (${booking.program.code})
Shoot Type: ${shootTypeLabel}
Location / Room: ${location}
Producer: ${booking.producer}
Crew: ${booking.crewRequired.join(', ') || '—'}
Agency Ref: ${booking.agencyRef || '—'}
Notes: ${booking.notes || '—'}

Booking ID: ${booking.id}
Auto-generated by THE STANDARD Production Booking`

    // NOTE: Service accounts cannot add attendees without Domain-Wide Delegation
    // (org policy denies it). We list the assigned crew in the description instead.
    // Crew see the event because they all subscribe to the shared calendar.
    const assignedList = (booking.assignedEmails || []).filter(Boolean).join(', ') || '—'
    const fullDescription = `${description}\n\nAssigned: ${assignedList}`

    const event = await calendar.events.insert({
      calendarId: CALENDAR_ID,
      requestBody: {
        summary: title,
        description: fullDescription,
        location,
        start: {
          dateTime: startTime.toISOString(),
          timeZone: 'Asia/Bangkok',
        },
        end: {
          dateTime: endTime.toISOString(),
          timeZone: 'Asia/Bangkok',
        },
        colorId: '11',
      },
    })

    return event.data.id || null
  } catch (e) {
    console.error('createCalendarEvent error:', e)
    return null
  }
}

export async function deleteCalendarEvent(eventId: string): Promise<boolean> {
  if (!process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL && !process.env.GOOGLE_SERVICE_ACCOUNT_JSON) {
    return false
  }
  try {
    const auth = getAuth()
    const calendar = google.calendar({ version: 'v3', auth })
    await calendar.events.delete({ calendarId: CALENDAR_ID, eventId })
    return true
  } catch (e) {
    console.error('deleteCalendarEvent error:', e)
    return false
  }
}

// Returns the public Google Calendar URL (htmlLink) for an event, so emails
// can link straight to the calendar event. Returns null if unavailable.
export async function getCalendarEventLink(eventId: string): Promise<string | null> {
  if (!process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL && !process.env.GOOGLE_SERVICE_ACCOUNT_JSON) {
    return null
  }
  try {
    const auth = getAuth()
    const calendar = google.calendar({ version: 'v3', auth })
    const res = await calendar.events.get({ calendarId: CALENDAR_ID, eventId })
    return res.data.htmlLink || null
  } catch (e) {
    console.error('getCalendarEventLink error:', e)
    return null
  }
}
