import { clsx, type ClassValue } from 'clsx'
import { format, parseISO } from 'date-fns'

export function cn(...inputs: ClassValue[]) {
  return clsx(inputs)
}

export function formatThaiDate(date: Date | string): string {
  const d = typeof date === 'string' ? parseISO(date) : date
  return format(d, 'd MMM yyyy')
}

export function formatDate(date: Date | string): string {
  const d = typeof date === 'string' ? parseISO(date) : date
  return format(d, 'yyyy-MM-dd')
}

export function formatDisplayDate(date: Date | string): string {
  const d = typeof date === 'string' ? parseISO(date) : date
  return format(d, 'EEE dd MMM yyyy')
}

export function shootTypeLabel(type: string): string {
  const map: Record<string, string> = {
    STUDIO: 'Studio',
    ON_LOCATION: 'On Location',
    REMOTE_ONLINE: 'Remote / Online',
    EVENT: 'Event',
  }
  return map[type] ?? type
}

export function categoryLabel(cat: string): string {
  const map: Record<string, string> = {
    RECURRING: 'Recurring',
    AGENCY_JOB: 'Agency Job',
    SERVICE_JOB: 'Service Job',
    INTERNAL: 'Internal',
  }
  return map[cat] ?? cat
}

export function statusLabel(status: string): string {
  const map: Record<string, string> = {
    REQUESTED: '[Requested]',
    ASSIGNED: 'Assigned',
    CONFIRMED: 'Confirmed',
    CANCELLED: 'Cancelled',
    COMPLETED: 'Completed',
  }
  return map[status] ?? status
}

export function statusColor(status: string): string {
  const map: Record<string, string> = {
    REQUESTED: 'bg-red-100 text-red-700',
    ASSIGNED: 'bg-yellow-100 text-yellow-700',
    CONFIRMED: 'bg-green-100 text-green-700',
    CANCELLED: 'bg-gray-100 text-gray-500',
    COMPLETED: 'bg-blue-100 text-blue-700',
  }
  return map[status] ?? 'bg-gray-100 text-gray-800'
}

export function buildCalendarPacket(booking: {
  outletName: string
  outletCode: string
  programName: string
  programCode: string
  shootDate: Date | string
  callTime: string
  estimatedWrap?: string | null
  shootType: string
  locationName?: string | null
  producer: string
  creative?: string[]
  crewRequired?: string[]
  agencyRef?: string | null
  notes?: string | null
  episodes: Array<{ episodeId: string; title: string }>
}): string {
  const d = typeof booking.shootDate === 'string' ? parseISO(booking.shootDate) : booking.shootDate
  const dateStr = format(d, 'yyyy-MM-dd')
  const wrapStr = booking.estimatedWrap ? `→ ${booking.estimatedWrap}` : ''
  const epCount = booking.episodes.length
  const location =
    booking.shootType === 'STUDIO'
      ? `Studio`
      : booking.locationName || booking.shootType.replace('_', ' ')

  const epList = booking.episodes
    .map(e => `  • ${e.episodeId} — ${e.title}`)
    .join('\n')

  const crew = booking.crewRequired?.join(', ') || '—'
  const creative = booking.creative?.join(', ') || '—'

  const title =
    epCount === 1
      ? `[${booking.outletCode}] ${booking.programName} — ${booking.episodes[0].title}`
      : `[${booking.outletCode}] ${booking.programName} — ${epCount} EPs (${booking.callTime}${wrapStr})`

  return `EVENT TITLE:
${title}

TIME: ${booking.callTime} ${wrapStr}
DATE: ${dateStr}
LOCATION: ${location}

──────────────────────────────
Production Project
Episode IDs:
${epList}

Outlet: ${booking.outletName} (${booking.outletCode})
Program: ${booking.programName} (${booking.programCode})
Shoot Type: ${shootTypeLabel(booking.shootType)}
Producer: ${booking.producer}
Creative/Host: ${creative}
Crew: ${crew}

NAS: /Production/${format(d, 'yyyy/MM')}/${booking.outletCode}-${format(d, 'yyMMdd')}-${booking.programCode}/
Agency Ref: ${booking.agencyRef || '—'}
Notes: ${booking.notes || '—'}
──────────────────────────────
Auto-generated by THE STANDARD Production Booking
${format(new Date(), 'yyyy-MM-dd HH:mm')} BKK`
}
